Traceback (most recent call last):
  File "c:\Users\estevao.santos\Documents\GitHub\Automation_Boring_Stuff\12 - Debugging\tempCodeRunnerFile.py", line 7, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
Traceback (most recent call last):
  File "c:/Users/estevao.santos/Documents/GitHub/Automation_Boring_Stuff/12 - Debugging/1 - Raise_Assert_Statements.py", line 7, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
